PROGRAM=main
EXTRA_COMPONENTS = extras/mbedtls extras/paho_mqtt_c extras/dhcpserver
FLASH_SIZE=32

PROGRAM_SRC_DIR=. ./includes
PROGRAM_INC_DIR=. ./includes

include /home/shadowfox/Projects/Toolchains/esp-open-rtos/common.mk